// 20 questões seed para popular o banco de dados
// Distribuídas nos 6 macrotemas do Revalida

export const QUESTOES_SEED = [
  // Clínica Médica (4 questões)
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "A",
    numero: 1,
    enunciado: "Paciente de 65 anos, hipertenso, apresenta dor torácica em aperto há 30 minutos, irradiada para membro superior esquerdo. ECG mostra supradesnivelamento de ST em DII, DIII e aVF. Qual a conduta inicial mais adequada?",
    alternativa_a: "Solicitar ecocardiograma e aguardar resultado",
    alternativa_b: "Administrar AAS, clopidogrel, heparina e encaminhar para angioplastia primária",
    alternativa_c: "Prescrever anti-hipertensivo e analgésico",
    alternativa_d: "Realizar teste ergométrico",
    alternativa_e: "Solicitar troponina e aguardar resultado",
    correta: "B",
    tema: "Clínica Médica",
    subtema: "Cardiologia - Síndrome Coronariana Aguda",
    dificuldade: 3,
    tags: ["IAM", "emergência", "cardiologia"],
    fontes_base: [{ titulo: "Diretriz de IAM com Supradesnivelamento de ST", ano: 2020 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "A",
    numero: 2,
    enunciado: "Mulher de 45 anos com diabetes mellitus tipo 2 há 10 anos, em uso de metformina 2g/dia, apresenta HbA1c de 8,5%. Qual a melhor conduta terapêutica?",
    alternativa_a: "Manter metformina e orientar dieta",
    alternativa_b: "Adicionar insulina NPH",
    alternativa_c: "Adicionar inibidor de SGLT2 ou agonista de GLP-1",
    alternativa_d: "Substituir metformina por sulfonilureia",
    alternativa_e: "Suspender metformina e iniciar insulina regular",
    correta: "C",
    tema: "Clínica Médica",
    subtema: "Endocrinologia - Diabetes",
    dificuldade: 2,
    tags: ["diabetes", "tratamento", "endocrinologia"],
    fontes_base: [{ titulo: "Diretriz SBD 2023", ano: 2023 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "A",
    numero: 3,
    enunciado: "Paciente de 70 anos com DPOC grave apresenta dispneia progressiva e cianose. Gasometria: pH 7,25, PaCO2 65mmHg, PaO2 50mmHg, HCO3 28mEq/L. Qual o diagnóstico?",
    alternativa_a: "Acidose metabólica descompensada",
    alternativa_b: "Alcalose respiratória",
    alternativa_c: "Acidose respiratória aguda",
    alternativa_d: "Acidose respiratória crônica agudizada",
    alternativa_e: "Acidose mista",
    correta: "D",
    tema: "Clínica Médica",
    subtema: "Pneumologia - DPOC",
    dificuldade: 4,
    tags: ["DPOC", "gasometria", "pneumologia"],
    fontes_base: [{ titulo: "GOLD 2023", ano: 2023 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "A",
    numero: 4,
    enunciado: "Homem de 55 anos com cirrose hepática por hepatite C apresenta ascite volumosa. Paracentese mostra GASA >1,1 g/dL e PMN 280 células/mm³. Qual a conduta?",
    alternativa_a: "Iniciar antibiótico (ceftriaxona) imediatamente",
    alternativa_b: "Aguardar cultura do líquido ascítico",
    alternativa_c: "Prescrever apenas diurético",
    alternativa_d: "Solicitar nova paracentese em 48h",
    alternativa_e: "Indicar transplante hepático urgente",
    correta: "A",
    tema: "Clínica Médica",
    subtema: "Gastroenterologia - Peritonite Bacteriana Espontânea",
    dificuldade: 3,
    tags: ["cirrose", "PBE", "gastroenterologia"],
    fontes_base: [{ titulo: "Diretriz de Cirrose - SBH", ano: 2021 }],
  },

  // Ginecologia e Obstetrícia (3 questões)
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "B",
    numero: 5,
    enunciado: "Gestante de 32 semanas com PA 160x110 mmHg, proteinúria 3+, cefaleia e epigastralgia. Qual o diagnóstico e conduta?",
    alternativa_a: "Pré-eclâmpsia leve - tratar ambulatorialmente",
    alternativa_b: "Pré-eclâmpsia grave - internar e estabilizar para parto",
    alternativa_c: "Hipertensão gestacional - apenas observar",
    alternativa_d: "Eclâmpsia - anticonvulsivante e parto imediato",
    alternativa_e: "Hipertensão crônica - ajustar anti-hipertensivo",
    correta: "B",
    tema: "Ginecologia e Obstetrícia",
    subtema: "Obstetrícia - Pré-eclâmpsia",
    dificuldade: 2,
    tags: ["pré-eclâmpsia", "emergência obstétrica", "hipertensão"],
    fontes_base: [{ titulo: "Manual Técnico Gestação de Alto Risco - MS", ano: 2022 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "B",
    numero: 6,
    enunciado: "Mulher de 28 anos com sangramento uterino anormal há 6 meses, ciclos irregulares. USG transvaginal normal. Qual o próximo passo?",
    alternativa_a: "Histeroscopia diagnóstica",
    alternativa_b: "Dosagem de TSH, prolactina e avaliação de coagulopatias",
    alternativa_c: "Iniciar anticoncepcional oral imediatamente",
    alternativa_d: "Curetagem uterina",
    alternativa_e: "Ressonância magnética de pelve",
    correta: "B",
    tema: "Ginecologia e Obstetrícia",
    subtema: "Ginecologia - Sangramento Uterino Anormal",
    dificuldade: 3,
    tags: ["sangramento", "ginecologia", "investigação"],
    fontes_base: [{ titulo: "Protocolo FEBRASGO - SUA", ano: 2021 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "B",
    numero: 7,
    enunciado: "Primigesta de 38 semanas em trabalho de parto com 8cm de dilatação. BCF 90 bpm persistente. Qual a conduta?",
    alternativa_a: "Aguardar dilatação completa",
    alternativa_b: "Cesariana de emergência",
    alternativa_c: "Administrar ocitocina",
    alternativa_d: "Fórcipe de alívio",
    alternativa_e: "Reposicionar a gestante",
    correta: "B",
    tema: "Ginecologia e Obstetrícia",
    subtema: "Obstetrícia - Sofrimento Fetal",
    dificuldade: 2,
    tags: ["parto", "emergência", "sofrimento fetal"],
    fontes_base: [{ titulo: "Diretriz de Assistência ao Parto - MS", ano: 2021 }],
  },

  // Pediatria (3 questões)
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "C",
    numero: 8,
    enunciado: "Lactente de 4 meses com febre de 39°C há 2 dias, irritabilidade e recusa alimentar. Exame físico sem foco aparente. Qual a conduta?",
    alternativa_a: "Prescrever antitérmico e reavaliação em 48h",
    alternativa_b: "Solicitar hemograma, PCR, urina tipo 1 e urocultura, iniciar antibiótico empírico",
    alternativa_c: "Solicitar apenas hemograma",
    alternativa_d: "Observação domiciliar",
    alternativa_e: "Prescrever antiviral",
    correta: "B",
    tema: "Pediatria",
    subtema: "Infectologia Pediátrica - Febre sem Sinais Localizatórios",
    dificuldade: 3,
    tags: ["febre", "lactente", "infecção"],
    fontes_base: [{ titulo: "Tratado de Pediatria SBP", ano: 2022 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "C",
    numero: 9,
    enunciado: "Criança de 2 anos com diarreia aquosa há 3 dias, vômitos, mucosas secas, olhos fundos, sinal da prega positivo. Qual o grau de desidratação e conduta?",
    alternativa_a: "Desidratação leve - TRO via oral",
    alternativa_b: "Desidratação grave - hidratação venosa rápida",
    alternativa_c: "Sem desidratação - orientação domiciliar",
    alternativa_d: "Desidratação moderada - TRO supervisionada",
    alternativa_e: "Choque hipovolêmico - UTI",
    correta: "B",
    tema: "Pediatria",
    subtema: "Gastroenterologia - Desidratação",
    dificuldade: 2,
    tags: ["desidratação", "diarreia", "emergência"],
    fontes_base: [{ titulo: "Manual AIDPI - MS", ano: 2020 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "C",
    numero: 10,
    enunciado: "RN de 3 dias com icterícia até abdome, bilirrubina total 18 mg/dL (indireta 17 mg/dL). Qual a conduta?",
    alternativa_a: "Observação e reavaliação em 24h",
    anternativa_b: "Fototerapia imediata",
    alternativa_c: "Exsanguineotransfusão",
    alternativa_d: "Alta hospitalar com orientação",
    alternativa_e: "Suspender aleitamento materno",
    correta: "B",
    tema: "Pediatria",
    subtema: "Neonatologia - Icterícia Neonatal",
    dificuldade: 3,
    tags: ["icterícia", "neonato", "fototerapia"],
    fontes_base: [{ titulo: "Diretriz de Hiperbilirrubinemia - SBP", ano: 2021 }],
  },

  // Cirurgia (3 questões)
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "D",
    numero: 11,
    enunciado: "Homem de 40 anos com dor abdominal intensa em FID há 12 horas, febre, Blumberg positivo. Leucócitos 18.000. Qual o diagnóstico e conduta?",
    alternativa_a: "Apendicite aguda - laparotomia/videolaparoscopia",
    alternativa_b: "Gastroenterite - tratamento clínico",
    alternativa_c: "Diverticulite - antibiótico",
    alternativa_d: "Obstrução intestinal - sonda nasogástrica",
    alternativa_e: "Colecistite - colecistectomia",
    correta: "A",
    tema: "Cirurgia",
    subtema: "Cirurgia Geral - Apendicite",
    dificuldade: 2,
    tags: ["apendicite", "abdome agudo", "emergência"],
    fontes_base: [{ titulo: "Sabiston - Tratado de Cirurgia", ano: 2022 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "D",
    numero: 12,
    enunciado: "Paciente politraumatizado com fratura de fêmur, PA 80x50 mmHg, FC 130 bpm, palidez cutânea. Qual a prioridade no atendimento?",
    alternativa_a: "Imobilizar fratura",
    alternativa_b: "Reposição volêmica agressiva e controle de hemorragia",
    alternativa_c: "Solicitar radiografias",
    alternativa_d: "Analgesia potente",
    alternativa_e: "Transferir para centro cirúrgico",
    correta: "B",
    tema: "Cirurgia",
    subtema: "Trauma - Choque Hemorrágico",
    dificuldade: 3,
    tags: ["trauma", "choque", "emergência"],
    fontes_base: [{ titulo: "ATLS - Advanced Trauma Life Support", ano: 2022 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "D",
    numero: 13,
    enunciado: "Mulher de 50 anos com dor em hipocôndrio direito pós-prandial, náuseas. USG mostra cálculos na vesícula. Qual a conduta?",
    alternativa_a: "Colecistectomia videolaparoscópica eletiva",
    alternativa_b: "Tratamento clínico com ácido ursodesoxicólico",
    alternativa_c: "Colecistectomia de urgência",
    alternativa_d: "Dieta e analgésicos",
    alternativa_e: "Litotripsia",
    correta: "A",
    tema: "Cirurgia",
    subtema: "Cirurgia Geral - Colelitíase",
    dificuldade: 2,
    tags: ["vesícula", "colelitíase", "cirurgia eletiva"],
    fontes_base: [{ titulo: "Diretrizes Brasileiras de Colecistite", ano: 2021 }],
  },

  // Medicina Preventiva e Social (4 questões)
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "E",
    numero: 14,
    enunciado: "Em uma UBS, você identifica surto de diarreia em uma comunidade. Qual a primeira medida de vigilância epidemiológica?",
    alternativa_a: "Prescrever antibiótico para todos",
    alternativa_b: "Notificar imediatamente e investigar fonte comum",
    alternativa_c: "Solicitar exames de todos os moradores",
    alternativa_d: "Orientar isolamento domiciliar",
    alternativa_e: "Encaminhar para hospital",
    correta: "B",
    tema: "Medicina Preventiva e Social",
    subtema: "Vigilância Epidemiológica",
    dificuldade: 2,
    tags: ["vigilância", "surto", "notificação"],
    fontes_base: [{ titulo: "Guia de Vigilância em Saúde - MS", ano: 2022 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "E",
    numero: 15,
    enunciado: "Gestante de 16 semanas, sem pré-natal prévio. Qual a sequência correta de exames de rotina?",
    alternativa_a: "Apenas ultrassom obstétrico",
    alternativa_b: "Hemograma, glicemia, VDRL, HIV, toxoplasmose, tipagem sanguínea, EAS, USG",
    alternativa_c: "Apenas tipagem sanguínea e USG",
    alternativa_d: "Hemograma e glicemia",
    alternativa_e: "Somente exames se sintomas",
    correta: "B",
    tema: "Medicina Preventiva e Social",
    subtema: "Saúde da Mulher - Pré-natal",
    dificuldade: 2,
    tags: ["pré-natal", "atenção básica", "rastreamento"],
    fontes_base: [{ titulo: "Cadernos de Atenção Básica - Pré-natal", ano: 2022 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "E",
    numero: 16,
    enunciado: "Paciente de 60 anos, tabagista, sem sintomas. Qual rastreamento oncológico está indicado?",
    alternativa_a: "Colonoscopia, mamografia (se mulher), PSA (se homem)",
    alternativa_b: "TC de tórax anual para rastreio de câncer de pulmão",
    alternativa_c: "Nenhum rastreamento necessário",
    alternativa_d: "Apenas exame físico anual",
    alternativa_e: "PET-CT corpo inteiro",
    correta: "A",
    tema: "Medicina Preventiva e Social",
    subtema: "Rastreamento Oncológico",
    dificuldade: 3,
    tags: ["rastreamento", "prevenção", "câncer"],
    fontes_base: [{ titulo: "INCA - Diretrizes de Rastreamento", ano: 2023 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "E",
    numero: 17,
    enunciado: "Criança de 6 meses comparece para consulta de puericultura. Qual a vacina indicada nesta idade?",
    alternativa_a: "Tríplice viral",
    alternativa_b: "3ª dose de pentavalente e VIP",
    alternativa_c: "BCG",
    alternativa_d: "Hepatite A",
    alternativa_e: "HPV",
    correta: "B",
    tema: "Medicina Preventiva e Social",
    subtema: "Imunização",
    dificuldade: 2,
    tags: ["vacina", "calendário vacinal", "puericultura"],
    fontes_base: [{ titulo: "Calendário Nacional de Vacinação - MS", ano: 2024 }],
  },

  // Ética Médica (3 questões)
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "F",
    numero: 18,
    enunciado: "Paciente de 17 anos procura atendimento para contracepção. Os pais não sabem. Qual a conduta ética?",
    alternativa_a: "Recusar atendimento e exigir presença dos pais",
    alternativa_b: "Atender, prescrever método contraceptivo e manter sigilo",
    alternativa_c: "Atender mas informar os pais",
    alternativa_d: "Encaminhar para serviço social",
    alternativa_e: "Solicitar autorização judicial",
    correta: "B",
    tema: "Ética Médica",
    subtema: "Sigilo e Autonomia do Adolescente",
    dificuldade: 3,
    tags: ["ética", "adolescente", "sigilo"],
    fontes_base: [{ titulo: "Código de Ética Médica - CFM", ano: 2019 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "F",
    numero: 19,
    enunciado: "Paciente terminal, lúcido, recusa tratamento de suporte. Família insiste no tratamento. Qual a conduta?",
    alternativa_a: "Seguir desejo da família",
    alternativa_b: "Respeitar autonomia do paciente",
    alternativa_c: "Solicitar parecer judicial",
    alternativa_d: "Iniciar tratamento mesmo sem consentimento",
    alternativa_e: "Transferir para outro médico",
    correta: "B",
    tema: "Ética Médica",
    subtema: "Autonomia e Terminalidade",
    dificuldade: 2,
    tags: ["ética", "autonomia", "cuidados paliativos"],
    fontes_base: [{ titulo: "Resolução CFM 1995/2012 - Diretivas Antecipadas", ano: 2012 }],
  },
  {
    ano: 2024,
    prova: "REVALIDA",
    caderno: "F",
    numero: 20,
    enunciado: "Médico presencia colega realizando procedimento sob efeito de álcool. Qual a conduta ética?",
    alternativa_a: "Ignorar para não prejudicar o colega",
    alternativa_b: "Notificar ao CRM e impedir o procedimento",
    alternativa_c: "Apenas conversar com o colega depois",
    alternativa_d: "Avisar apenas a chefia",
    alternativa_e: "Documentar mas não tomar atitude",
    correta: "B",
    tema: "Ética Médica",
    subtema: "Responsabilidade Profissional",
    dificuldade: 2,
    tags: ["ética", "responsabilidade", "denúncia"],
    fontes_base: [{ titulo: "Código de Ética Médica - CFM", ano: 2019 }],
  },
];
