// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bora Revalidar - Estude para o Revalida com IA",
  description: "Plataforma completa de estudos para o Revalida com questões, simulados, flashcards e inteligência artificial",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${inter.variable} font-inter antialiased`}
        style={{
          background: "linear-gradient(135deg, #0D1B2A 0%, #1B4332 100%)",
          minHeight: "100vh",
        }}
      >
        {children}
      </body>
    </html>
  );
}
